# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty

# Setup
title: Deep Network GmbH
tagline: "Developers' Blog"
description: 'A blog by developers at Deep Network GmbH'
url: https://deepnetwork.com
baseurl: /blog
paginate: 5
future: true
plugins:
  - jekyll-feed # atom
  - jekyll-paginate

# About/contact
author:
  name: Y Furkan Fidan
  url: http://www.deepnetwork.com
  email: furkan.fidan@deepnetwork.com

# Custom vars
version: 1.0.0
