# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty

# Setup
title:               Deep Network GMBH
tagline:             "Developers' Blog"
description:         'A blog by Developers at Deep Network GMBH'
url:                 https://deepnetworkgmbh.github.io/blog/
baseurl:             https://deepnetworkgmbh.github.io/blog/
paginate:            5
future: true
plugins:
    - jekyll-feed

# About/contact
author:
  name:              Y Furkan Fidan
  url:               http://www.deepnetwork.com
  email:             furkan.fidan@deepnetwork.com

# Custom vars
version:             1.0.0

