apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod-d-node-1
  labels:
    env: test
spec:
  containers:
  - name: ssh-pod-d-node-1
    image: ahdepe/simple-ssh-pod
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k8s-agentpool1-37464322-vmss000001
