apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod-a-node-0
  labels:
    env: test
spec:
  containers:
  - name: ssh-pod-a-node-0
    image: ahdepe/simple-ssh-pod
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k8s-agentpool1-37464322-vmss000000
